-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })

-- DMS_STARTUP_BEGIN
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
end)
-- DMS_STARTUP_END

hl.config({
	input = {
		-- empty inherits XKB_DEFAULT_LAYOUT (libxkbcommon), falls back to "us"
		kb_layout = "",
		numlock_by_default = true,
		follow_mouse = 0,
		touchpad = {
			tap_to_click = true,
			natural_scroll = true,
		},
	},
	general = {
		gaps_in = 5,
		gaps_out = 5,
		border_size = 2,
		layout = "dwindle",
	},
	decoration = {
		rounding = 12,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = true,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
})

hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "default" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "default" })

hl.window_rule({ match = { class = "^(org\\.wezfurlong\\.wezterm)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.)" }, rounding = 12 })
hl.window_rule({ match = { class = "^(gnome-control-center)$" }, tile = true })
hl.window_rule({ match = { class = "^(pavucontrol)$" }, tile = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(gnome-calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(galculator)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Nautilus)$" }, float = true })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
hl.window_rule({
	match = { class = "^(steam)$", title = "^(notificationtoasts)" },
	no_initial_focus = true,
	pin = true,
})
hl.window_rule({
	match = { class = "^(firefox)$", title = "^(Picture-in-Picture)$" },
	float = true,
})
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })

-- blkcat's overlay is a transparent X11 window the size of the game window (class
-- "blkcat", set by src/features/overlay.cpp). Hyprland's blur is on by default
-- (decoration:blur:enabled = true, ignore_opacity = true), so it replaces the
-- game behind that whole rectangle with a blurred copy: the overlay makes the
-- game look blurred. Exclude the overlay from blur, plus the shadow and
-- open/close animation, which a full-screen dock-type window has no use for.
--
-- no_focus / no_initial_focus matter too: the overlay is click-through (empty
-- input shape), so Hyprland never moves focus *off* it once it has it - and then
-- a window-targeted bind such as fullscreen hits the overlay instead of CS2.
-- Hyprland fullscreens the overlay, marks the game invisible (hyprctl clients:
-- cs2 vis=false) and the game "disappears" until you unfullscreen.
hl.window_rule({
	match = { class = "^blkcat$" },
	no_blur = true,
	no_shadow = true,
	no_anim = true,
	no_focus = true,
	no_initial_focus = true,
})

hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")

------------------------------
---- KEYBINDS (personal) ----
------------------------------

-- Kept here instead of dms/binds-user.lua on purpose: DMS rewrites that file from
-- its Settings → Keyboard Shortcuts page, while binds in this file are read-only
-- to it. dms/binds.lua (DMS defaults) and dms/binds-user.lua (overrides of those
-- defaults) are required above too — bind a key in exactly one of the three files,
-- because Hyprland runs every bind that matches a key.
--
-- Provided by the DMS defaults already: SUPER + Q close window, SUPER + F maximize,
-- SUPER + SHIFT + F fullscreen, SUPER + T ghostty, SUPER + space launcher
-- (spotlight), SUPER + V floating / SUPER + M Spotify / SUPER + Y YouTube (the
-- overrides in dms/binds-user.lua), plus media, brightness and screenshot keys.

-- Programs used by the binds below (change to taste).
local browser = "chromium"

-- Windows
hl.bind("SUPER + SHIFT + Q", hl.dsp.window.kill(), { description = "Force quit window" })

-- Extra launchers
hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"), { description = "kitty" })
hl.bind("SUPER + B", hl.dsp.exec_cmd("chromium"), { description = "Chromium" })

-- Apps
hl.bind("SUPER + S", hl.dsp.exec_cmd("steam"), { description = "Steam" })
hl.bind("SUPER + A", hl.dsp.exec_cmd(browser .. " --app=https://chatgpt.com"), { description = "ChatGPT web app" })
hl.bind("SUPER + SHIFT + A", hl.dsp.exec_cmd(browser .. " --app=https://claude.ai"), { description = "Claude web app" })
hl.bind("SUPER + G", hl.dsp.exec_cmd(browser .. " --app=https://github.com"), { description = "GitHub web app" })

-- DMS actions relocated off the keys taken above
hl.bind("SUPER + SHIFT + V", hl.dsp.exec_cmd("dms ipc call clipboard toggle"), { description = "Clipboard history" })
hl.bind("SUPER + SHIFT + Y", hl.dsp.exec_cmd("dms ipc call dash toggle wallpaper"), { description = "Dashboard: wallpaper" })
