-- User keybinds — the DMS "binds-user" fragment: overrides of DMS defaults only.
--
-- 2026-09-27: rewritten. Why this file is now short:
--   hyprland.lua requires *both* dms/binds.lua (DMS's defaults) and this file, and
--   Hyprland dispatches every bind that matches a key. The reinstall on
--   2026-09-27 copied the whole default set in here as well, so every key was
--   bound twice: SUPER + space ran "spotlight toggle" twice, which opened the
--   launcher and toggled it straight back shut (the flicker), and volume
--   /brightness/screenshot keys stepped twice. Now each key is bound once.
--
-- Rules:
--   dms/binds.lua        DMS defaults, regenerated by DMS — do not edit.
--   dms/binds-user.lua   <- this file. Re-point a default with hl.unbind() first,
--                        then bind it again. DMS writes negative overrides here
--                        too (that is how its Settings → Keyboard Shortcuts page
--                        removes a default) and reads this file back for display.
--   hyprland.lua         personal keys DMS knows nothing about, in the
--                        "KEYBINDS (personal)" section — DMS never rewrites it.
-- After editing: `hyprctl reload`.

-- SUPER + V → toggle floating (the DMS default was clipboard history).
-- Clipboard history moved to SUPER + SHIFT + V (hyprland.lua).
hl.unbind("SUPER + V")
hl.bind("SUPER + V", hl.dsp.window.float({ action = "toggle" }), { description = "Toggle floating" })

-- SUPER + M → Spotify (the DMS default was the process list).
-- The process list is still on CTRL + ALT + Delete.
hl.unbind("SUPER + M")
hl.bind("SUPER + M", hl.dsp.exec_cmd("spotify"), { description = "Spotify" })

-- SUPER + Y → YouTube web app (the DMS default was the wallpaper dashboard).
-- The dashboard moved to SUPER + SHIFT + Y (hyprland.lua).
hl.unbind("SUPER + Y")
hl.bind("SUPER + Y", hl.dsp.exec_cmd("chromium --app=https://www.youtube.com"), { description = "YouTube web app" })
